//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 05:00:06 PM MSK 
//


package main.models.pojo;


public class Admin
    extends User
{

    protected String adminSpecificValue;


    public String getAdminSpecificValue() {
        return adminSpecificValue;
    }

    public void setAdminSpecificValue(String value) {
        this.adminSpecificValue = value;
    }

}
