//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 05:00:06 PM MSK 
//


package main.models.pojo;

public class Leaser
    extends User
{

    protected String leaserSpecificValue;

    public Leaser() {
    }

    public Leaser(String firstName, String secondName, String lastName,
                  String phoneNumber, String email) {
        super(firstName, secondName, lastName, phoneNumber, email);
    }

    public Leaser(int id, String firstName, String secondName, String lastName,
                  String phoneNumber, String email,
                  boolean isAdmin, boolean isActive, boolean isDeleted) {
        super(id, firstName, secondName, lastName, phoneNumber, email, isAdmin, isActive, isDeleted);
    }

    public String getLeaserSpecificValue() {
        return leaserSpecificValue;
    }

    public void setLeaserSpecificValue(String value) {
        this.leaserSpecificValue = value;
    }

}
