//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.04.22 at 05:00:06 PM MSK 
//


package models.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Leaser complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Leaser">
 *   &lt;complexContent>
 *     &lt;extension base="{}User">
 *       &lt;sequence>
 *         &lt;element name="leaserSpecificValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Leaser", propOrder = {
    "leaserSpecificValue"
})
public class Leaser
    extends User
{

    @XmlElement(required = true)
    protected String leaserSpecificValue;

    public Leaser() {
    }

    public Leaser(String firstName, String secondName, String lastName,
                  String phoneNumber, String email) {
        super(firstName, secondName, lastName, phoneNumber, email);
    }

    public Leaser(int id, String firstName, String secondName, String lastName,
                  String phoneNumber, String email,
                  boolean isAdmin, boolean isActive, boolean isDeleted) {
        super(id, firstName, secondName, lastName, phoneNumber, email, isAdmin, isActive, isDeleted);
    }

    /**
     * Gets the value of the leaserSpecificValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLeaserSpecificValue() {
        return leaserSpecificValue;
    }

    /**
     * Sets the value of the leaserSpecificValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLeaserSpecificValue(String value) {
        this.leaserSpecificValue = value;
    }

}
